apiVersion: v1
kind: Service
metadata:
  name: blog-service-production
  namespace: macross-production
spec:
  selector:
    app: blog-production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
