apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-deployment-production
  namespace: production
spec:
  selector:
    matchLabels:
      app: pesbuk-production
  replicas: 1
  template:
    metadata:
      namespace: production
      labels:
        app: pesbuk-production
    spec:
      volumes:
      - name: config-secret
        configMap:
          name: pesbuk-configmap-production

      containers:
      - name: pesbuk-production
        image: 123456789.dkr.ecr.us-east-1.amazonaws.com/awn-pesbuk:production
        resources: {}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-secret
          mountPath: "/var/www/html/config.php"
          subPath: "config.php"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-production
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-production
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-production
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-production
              key: DB_NAME
