apiVersion: v1
kind: Service
metadata:
  name: landingpage-service-production
  namespace: production
spec:
  selector:
    app: landingpage-production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
